backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "images/uploads"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.json"
        fields:
          - {label: About Me, name: aboutBody, widget: string}
          - {label: Currently Appearing, name: currentlyAppearing, widget: string}
          - label: "Recent Jobs"
            name: "recentJobs"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Year", name: "year", widget: "string"}
              - {label: "Type", name: "type", widget: "string"}
              - {label: "Role", name: "role", widget: "string"}
              - {label: "Company", name: "company", widget: "string"}
              - {label: "Director", name: "director", widget: "string"}
      - label: "Media Page"
        name: "media"
        file: "content/media.json"
        fields:
          - {label: Showreel URL, name: showreel, widget: string}
          - label: "Video Library"
            name: "videoLibrary"
            widget: "list"
            fields:
              - {label: "Video Thumbnail", name: "thumbnail", widget: "image"}
              - {label: "Video Title", name: "title", widget: "string"}
              - {label: "Video Src", name: "src", widget: "string"}
          - label: "Image Gallery"
            name: "imageGallery"
            widget: "list"
            fields:
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Image Description", name: "desc", widget: "string"}
              - {label: "Image Copyright", name: "copy", widget: "string"}         
              
site_url: https://isobellepippin.netlify.app