backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Headshots"
        name: "headshots"
        file: "content/headshots.json"
        fields:
          - label: "Headshot Collection"
            name: "headshotList"
            widget: "list"
            fields:
              - {label: "Image", name: "image", widget: "image"}
      - label: "Home Page"
        name: "home"
        file: "content/home.json"
        fields:
          - {label: "About Me", name: "aboutBody", widget: "string"}
          - {label: "Currently Appearing", name: "currentlyAppearing", widget: "string"}
          - label: "Recent Jobs"
            name: "recentJobs"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Year", name: "year", widget: "string"}
              - {label: "Type", name: "type", widget: "string"}
              - {label: "Role", name: "role", widget: "string"}
              - {label: "Company", name: "company", widget: "string"}
              - {label: "Director", name: "director", widget: "string"}
      - label: "Media Page"
        name: "media"
        file: "content/media.json"
        fields:
          - {label: Showreel URL, name: showreel, widget: string}
          - label: "Video Library"
            name: "videoLibrary"
            widget: "list"
            fields:
              - {label: "Video Thumbnail", name: "thumbnail", widget: "image"}
              - {label: "Video Title", name: "title", widget: "string"}
              - {label: "Video Src", name: "src", widget: "string"}
          - label: "Image Gallery"
            name: "imageGallery"
            widget: "list"
            fields:
              - {label: "Image", name: "src", widget: "image"}
              - {label: "Image Description", name: "desc", widget: "string"}
              - {label: "Image Copyright", name: "copy", widget: "string"}   
      - label: "Creative Projects Page"
        name: "creativeProjects"
        file: "content/creativeProjects.json"
        fields:
          - label: "Maxwell Mysteries"
            name: "maxwellMysteries"
            widget: "list"
            fields:
              - {label: "Product ID Number", name: "productID", widget: "number", value_type: "int"}
              - {label: "Game Title", name: 'gameTitle', widget: "string"}
              - {label: "Game Category", name: 'gameCategory', widget: "string", default: "print and play"}
              - {label: "Image", name: "src", widget: "image"}
              - {label: "Video URL", name: 'videoSrc', widget: "string"}
              - {label: "Use Video Trailer?", name: "useVideoTrailer", widget: "boolean", default: true}
              - {label: "Game Story", name: "gameStory", widget: "text"}
              - {label: "Game Description", name: "gameDescription", widget: "text"}
              - {label: "Price", name: 'price', widget: "string"}
              - label: "What They Need"
                name: "requirementsList" 
                widget: "list"
                fields: 
                  - {label: "Requirement", name: 'requirement', widget: "string"}
          - label: "Art Gallery"
            name: "artGallery"
            widget: "list"
            fields:
              - {label: "Image", name: "src", widget: "image"}
              - {label: "Image Description", name: "desc", widget: "string"}
      - label: "Contact Page"
        name: "contact"
        file: "content/contact.json"
        fields:      
          - label: "Agent Details"
            name: "agent"
            widget: "object"
            fields: 
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Address", name: "address", widget: "string"}
              - {label: "Phone", name: "phone", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}
              - label: "Website"
                name: "website"
                widget: "object"
                fields:
                  - {label: "Displayed Address", name: "display", widget: "string"}
                  - {label: "URL", name: "url", widget: "string"}
              
site_url: https://isobellepippin.netlify.app

# Copyright (c) 2016 Netlify <team@netlify.com>

# MIT License

# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:

# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.