backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "images/uploads"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.json"
        fields:
          - {label: About Me, name: aboutBody, widget: string}
          - {label: Currently Appearing, name: currentlyAppearing, widget: string}
  - label: "Recent Jobs"
    name: "recentJobs"
    file: "content/jobs.json"
    widget: "list"
    collapsed: false
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Type", name: "type", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Company", name: "company", widget: "string"}
      - {label: "Director", name: "director", widget: "string"}

site_url: https://isobellepippin.netlify.app